# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: g:/EMICAP/semicap/semicap.srcs/sources_1/bd/semicap/ip/semicap_hipero_sem_0/semicap_hipero_sem_0.xci
# IP: The module: 'semicap_hipero_sem_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/EMICAP/semicap/semicap.srcs/sources_1/bd/semicap/ip/semicap_hipero_sem_0/synth/semicap_hipero_sem_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'semicap_hipero_sem_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: g:/EMICAP/semicap/semicap.srcs/sources_1/bd/semicap/ip/semicap_hipero_sem_0/semicap_hipero_sem_0.xci
# IP: The module: 'semicap_hipero_sem_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/EMICAP/semicap/semicap.srcs/sources_1/bd/semicap/ip/semicap_hipero_sem_0/synth/semicap_hipero_sem_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'semicap_hipero_sem_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
