# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/payload_partition/payload_partition.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==payload_partition || ORIG_REF_NAME==payload_partition} -quiet] -quiet

# IP: bd/payload_partition/ip/payload_partition_axi_cdma_0_0/payload_partition_axi_cdma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==payload_partition_axi_cdma_0_0 || ORIG_REF_NAME==payload_partition_axi_cdma_0_0} -quiet] -quiet

# XDC: bd/payload_partition/payload_partition_ooc.xdc
