# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Projects/Hipero/svn/dev/fpga/ip_projects/semicap_engine/semicap_engine.srcs/sources_1/ip/fifo_mon_cmd/fifo_mon_cmd.xci
# IP: The module: 'fifo_mon_cmd' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Projects/Hipero/svn/dev/fpga/ip_projects/semicap_engine/semicap_engine.srcs/sources_1/ip/fifo_mon_cmd/fifo_mon_cmd.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_mon_cmd'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Projects/Hipero/svn/dev/fpga/ip_projects/semicap_engine/semicap_engine.srcs/sources_1/ip/fifo_mon_cmd/fifo_mon_cmd_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_mon_cmd'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/Projects/Hipero/svn/dev/fpga/ip_projects/semicap_engine/semicap_engine.srcs/sources_1/ip/fifo_mon_cmd/fifo_mon_cmd.xci
# IP: The module: 'fifo_mon_cmd' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Projects/Hipero/svn/dev/fpga/ip_projects/semicap_engine/semicap_engine.srcs/sources_1/ip/fifo_mon_cmd/fifo_mon_cmd.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_mon_cmd'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Projects/Hipero/svn/dev/fpga/ip_projects/semicap_engine/semicap_engine.srcs/sources_1/ip/fifo_mon_cmd/fifo_mon_cmd_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_mon_cmd'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
