# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: g:/EMICAP/semicap/semicap.srcs/sources_1/bd/semicap/ip/semicap_axi_hwicap_0_0/semicap_axi_hwicap_0_0.xci
# IP: The module: 'semicap_axi_hwicap_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/EMICAP/semicap/semicap.srcs/sources_1/bd/semicap/ip/semicap_axi_hwicap_0_0/semicap_axi_hwicap_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'semicap_axi_hwicap_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: g:/EMICAP/semicap/semicap.srcs/sources_1/bd/semicap/ip/semicap_axi_hwicap_0_0/semicap_axi_hwicap_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'semicap_axi_hwicap_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: g:/EMICAP/semicap/semicap.srcs/sources_1/bd/semicap/ip/semicap_axi_hwicap_0_0/semicap_axi_hwicap_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'semicap_axi_hwicap_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: g:/EMICAP/semicap/semicap.srcs/sources_1/bd/semicap/ip/semicap_axi_hwicap_0_0/semicap_axi_hwicap_0_0.xci
# IP: The module: 'semicap_axi_hwicap_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/EMICAP/semicap/semicap.srcs/sources_1/bd/semicap/ip/semicap_axi_hwicap_0_0/semicap_axi_hwicap_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'semicap_axi_hwicap_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: g:/EMICAP/semicap/semicap.srcs/sources_1/bd/semicap/ip/semicap_axi_hwicap_0_0/semicap_axi_hwicap_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'semicap_axi_hwicap_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: g:/EMICAP/semicap/semicap.srcs/sources_1/bd/semicap/ip/semicap_axi_hwicap_0_0/semicap_axi_hwicap_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'semicap_axi_hwicap_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
