# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xcku040-ffva1156-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Projects/Hipero/svn/dev/fpga/ip_projects/semicap_engine/semicap_engine.cache/wt [current_project]
set_property parent.project_path D:/Projects/Hipero/svn/dev/fpga/ip_projects/semicap_engine/semicap_engine.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part xilinx.com:kcu105:part0:1.5 [current_project]
set_property ip_output_repo d:/Projects/Hipero/svn/dev/fpga/ip_projects/semicap_engine/semicap_engine.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  D:/Projects/Hipero/svn/dev/fpga/ip_projects/semicap_engine/semicap_engine.srcs/sources_1/new/icapArbiter.vhd
  D:/Projects/Hipero/svn/dev/fpga/ip_projects/semicap_engine/semicap_engine.srcs/sources_1/imports/srcs/minority_voter_status_latch.vhd
  D:/Projects/Hipero/svn/dev/fpga/ip_projects/semicap_engine/semicap_engine.srcs/sources_1/imports/srcs/sem_state_decoder.vhd
  D:/Projects/Hipero/svn/dev/fpga/ip_projects/semicap_engine/semicap_engine.srcs/sources_1/new/semicap_fsm.vhd
  D:/Projects/Hipero/svn/dev/fpga/ip_projects/semicap_engine/semicap_engine.srcs/sources_1/new/semicap_engine.vhd
}
read_ip -quiet D:/Projects/Hipero/svn/dev/fpga/ip_projects/semicap_engine/semicap_engine.srcs/sources_1/ip/fifo_mon_cmd/fifo_mon_cmd.xci
set_property used_in_implementation false [get_files -all d:/Projects/Hipero/svn/dev/fpga/ip_projects/semicap_engine/semicap_engine.srcs/sources_1/ip/fifo_mon_cmd/fifo_mon_cmd.xdc]
set_property used_in_implementation false [get_files -all d:/Projects/Hipero/svn/dev/fpga/ip_projects/semicap_engine/semicap_engine.srcs/sources_1/ip/fifo_mon_cmd/fifo_mon_cmd_ooc.xdc]

read_ip -quiet D:/Projects/Hipero/svn/dev/fpga/ip_projects/semicap_engine/semicap_engine.srcs/sources_1/ip/fifo_mon_stat/fifo_mon_stat.xci
set_property used_in_implementation false [get_files -all d:/Projects/Hipero/svn/dev/fpga/ip_projects/semicap_engine/semicap_engine.srcs/sources_1/ip/fifo_mon_stat/fifo_mon_stat.xdc]
set_property used_in_implementation false [get_files -all d:/Projects/Hipero/svn/dev/fpga/ip_projects/semicap_engine/semicap_engine.srcs/sources_1/ip/fifo_mon_stat/fifo_mon_stat_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top semicap_engine -part xcku040-ffva1156-2-e


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef semicap_engine.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file semicap_engine_utilization_synth.rpt -pb semicap_engine_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
