# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Projects/Hipero/svn/dev/fpga/ip_projects/payload_partition/payload_partition.srcs/sources_1/bd/payload_partition/ip/payload_partition_axi_cdma_0_0/payload_partition_axi_cdma_0_0.xci
# IP: The module: 'payload_partition_axi_cdma_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Projects/Hipero/svn/dev/fpga/ip_projects/payload_partition/payload_partition.srcs/sources_1/bd/payload_partition/ip/payload_partition_axi_cdma_0_0/payload_partition_axi_cdma_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'payload_partition_axi_cdma_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Projects/Hipero/svn/dev/fpga/ip_projects/payload_partition/payload_partition.srcs/sources_1/bd/payload_partition/ip/payload_partition_axi_cdma_0_0/payload_partition_axi_cdma_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'payload_partition_axi_cdma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/Projects/Hipero/svn/dev/fpga/ip_projects/payload_partition/payload_partition.srcs/sources_1/bd/payload_partition/ip/payload_partition_axi_cdma_0_0/payload_partition_axi_cdma_0_0.xci
# IP: The module: 'payload_partition_axi_cdma_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Projects/Hipero/svn/dev/fpga/ip_projects/payload_partition/payload_partition.srcs/sources_1/bd/payload_partition/ip/payload_partition_axi_cdma_0_0/payload_partition_axi_cdma_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'payload_partition_axi_cdma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Projects/Hipero/svn/dev/fpga/ip_projects/payload_partition/payload_partition.srcs/sources_1/bd/payload_partition/ip/payload_partition_axi_cdma_0_0/payload_partition_axi_cdma_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'payload_partition_axi_cdma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
